# Generated by Django 2.2.6 on 2019-10-10 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='程序类型', max_length=50)),
                ('intro', models.TextField(default='项目介绍')),
                ('icon', models.ImageField(default='defaultIC.png', upload_to='images/')),
                ('image', models.ImageField(default='defaultIM.png', upload_to='images/')),
                ('votes', models.IntegerField(default='1')),
                ('pub_date', models.DateTimeField()),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
